### ISSUE TITLE
Add ability to mimic all of WordPress' Plugin Info API data

### ISSUE THREAD

**Issue by thomasgriffin** [thomasgriffin/TGM-Updater#1]
There can be more data retrieved from the WordPress Plugin Info API that I have not accounted for, such as download counts, ratings and notes. These should be added to give plugin authors full control of the update experience and to integrate as seamlessly as possible into the WordPress update system.

**Comment by dovy** [comment]
Can you give us what you have already? I'd love to implement this.

**Comment by thomasgriffin** [comment]
I've determined that there is not much need for this with the new 4.0 plugin update modal. It shows the changelog by default, which is what people want to see, and this class does that well.
