### ISSUE TITLE
Create a meta plugin for MultiSite instances

### ISSUE THREAD

**Issue by thomasgriffin** [thomasgriffin/TGM-Updater#2]
Plugins utilizing this class (or any other class for that matter) inside of MultiSite will not receive updates if they are activated on an individual site basis (network activated MS plugins are fine). A meta plugin should be created that can be customized so that plugin authors can provide it as a complimentary download to ensure update parity across all types of WordPress installs.

**Comment by pippinsplugins** [comment]
You and I need to talk on this. I checked with my update class and it DOES work on multisite.

**Comment by thomasgriffin** [comment]
Just as a final comment, filtering `pre_set_site_transient_update_plugins` is preferred because ti caches the response. Because of the cached response, individual site plugins can still get updates because the download package is available. To be sure, the update will go away on the next transient update if the individual site is not visited, but for 99% of the cases, this will work just fine as users who visit the Updates page will likely update then and there.

**Comment by pippinsplugins** [comment]
Great to get that figured out :)

It should also be noted that it won't work to go to the Network admin and check for updates, but as long as the update check is done from the individual sites, it will work.
