### ISSUE TITLE
About future

### ISSUE THREAD

**Issue by unsalkorkmaz** [thomasgriffin/TGM-Updater#4]
Hi,
First of all, thanks a lot for releasing this project. Can we use it for themes?

**Comment by GaryJones** [comment]
Yes.

**Comment by unsalkorkmaz** [comment]
Nice, ty for answer. Btw, can i use it on products or should i wait for update? (warning says wait but 1 year past it seems)

**Comment by GaryJones** [comment]
It's fine to use it as is - it's been recommended for use at Theme Forest for a long while now.

**Comment by thomasgriffin** [comment]
I've same some big updates to this, and I plan on working on the counterpart API plugin as well to make this updater work full circle.
